app = "superdev-solana-server"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[env]
  RUST_LOG = "info" 